version: '3.8'

services:
  postgres:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_container
    ports:
      - "80:80"
    depends_on:
      - postgres
